INSERT INTO Document(html_content_eng, html_content_nl) VALUES('test_eng','test_nl');
INSERT INTO Document(html_content_eng, html_content_nl) VALUES('This is a test description.','Dit is een test beschrijving.');
INSERT INTO Document(html_content_eng, html_content_nl) VALUES('This is a project test description.','Dit is een project test beschrijving.');
INSERT INTO Attachment(name, file_location, document_id) VALUES('test attach', 'LOC test', 1);
INSERT  INTO study_field(field_name, is_active) VALUES ('chocolate eating', true);
INSERT  INTO study_field(field_name, is_active) VALUES ('test writing', false);
INSERT INTO research_group(name, abbreviation, logo_location, description_id, address, telephone_number, study_field, is_active) VALUES ('Boos', 'Bo', NULL, 1, NULL, NULL, 'chocolate eating', True);
INSERT INTO research_group(name, abbreviation, logo_location, description_id, address, telephone_number, study_field, is_active) VALUES ('Konijn', 'Ko', NULL, 1, NULL, NULL, 'chocolate eating', False);
INSERT INTO employee(name, email, office, extra_info, picture_location, research_group, title, is_intern, is_active) VALUES ('D Trump', NULL, NULL, NULL, NULL, 'Boos', 'PhD', true, true);
INSERT INTO project(title, max_students, description_id, research_group, is_active) VALUES ('RoboPro', 3, 1, 'Boos',True);
INSERT INTO project(title, max_students, description_id, research_group, is_active) VALUES ('RoboNo', 8, 2, 'Konijn',True);
INSERT INTO tag(tag) VALUES ('test_tag');
INSERT INTO type(type_name, is_active) VALUES ('test_type', true);
INSERT INTO project_has_tag(project, tag) VALUES (1, 'test_tag');
INSERT INTO project_has_type(project, type) VALUES (1, 'test_type');
INSERT INTO academic_year(year) VALUES (2021);
INSERT INTO project_has_year(project, year) VALUES (2, 2021);
INSERT INTO project(title, max_students, description_id, research_group, is_active) VALUES ('Search Me!', 1, 3, 'Konijn',False);
UPDATE project SET last_updated = '1/8/1999' WHERE project_id = 1;
UPDATE project SET last_updated = '1/8/2099' WHERE project_id = 2;
INSERT INTO guide(employee, project, guidance_type) VALUES (1, 1, 'Promotor');
INSERT INTO employee(name, email, office, extra_info, picture_location, research_group, title, is_intern, is_active) VALUES ('B Sanders', NULL, NULL, NULL, NULL, 'Konijn', 'Professor', true, false);
INSERT INTO student(name, student_id) VALUES ('Viet Aal', '1');
INSERT INTO student(name, student_id) VALUES ('Piet Sam Bakker', '3');
INSERT INTO project_registration(student, project) VALUES (1, 1);
INSERT INTO project_registration(student, project) VALUES (1, 2);
INSERT INTO "like"(student, project) VALUES ('1',1);
INSERT INTO session(student, start_of_session) VALUES ('1', '1/8/2014');
INSERT INTO session(student, start_of_session) VALUES ('3', '1/9/2014');
INSERT INTO project_click(session, project, time_of_click) VALUES (1,1,'23:50:02');
INSERT INTO query(session, time_of_query, search_terms) VALUES (1, '22:09:29', 'NO');
INSERT INTO link(project_1, project_2, match_percent) VALUES (1,2,0.3 )

