from src.models.attachment import *
from src.models.document import *
from src.models.employee import *
from src.models.guide import *
from src.models.like import *
from src.models.link import *
from src.models.project import *
from src.models.query import *
from src.models.research_group import *
from src.models.session import *
from src.models.student import *
from src.models.tag import *
from src.models.type import *
from src.models.registration import *
from src.models.click import *
